services:
  db:
    image: postgres:15
    container_name: helpdesk-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk_db
    ports:
      - "5432:5432"
  test_db:
    image: postgres:15
    container_name: helpdesk-test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_helpdesk_db # แยกชื่อฐานข้อมูลคนละก้อนชัดเจน
    ports:
      - "5433:5432"
  backend:
    build: ./backend
    container_name: helpdesk-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/helpdesk_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: helpdesk-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true